@ECHO OFF
python LFEDocumentClassifier.py -c km -sw -st -mc 51 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 52 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 53 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 54 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 55 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 56 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 57 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 58 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 59 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 60 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 61 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 62 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 63 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 64 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 65 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 66 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 67 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 68 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 69 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 70 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 71 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 72 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 73 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 74 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 75 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 76 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 77 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 78 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 79 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 80 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 81 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 82 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 83 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 84 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 85 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 86 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 87 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 88 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 89 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 90 -tr 1 -e 20 -s -fn kmeansExperiments.csv
PAUSE