@ECHO OFF
python LFEDocumentClassifier.py -c km -sw -st -mc 91 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 92 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 93 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 94 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 95 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 96 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 97 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 98 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 99 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 10 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 101 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 102 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 103 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 104 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 105 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 106 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 107 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 108 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 109 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 110 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 111 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 112 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 113 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 114 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 115 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 116 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 117 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 118 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 119 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 120 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 121 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 122 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 123 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 124 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 125 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 126 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 127 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 128 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 129 -tr 1 -e 20 -s -fn kmeansExperiments.csv
python LFEDocumentClassifier.py -c km -sw -st -mc 130 -tr 1 -e 20 -s -fn kmeansExperiments.csv
PAUSE